/*
 * Copyright (c) 2024 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define CONFIG_AMEBADPLUS 1
#define CONFIG_IMG1_FLASH 1
#define CONFIG_IMG2_FLASH 1
#define CONFIG_SUPPORT_ATCMD 1
#define CONFIG_ATCMD_MANUAL_TEST 1
#define CONFIG_ATCMD_NETWORK 1
#define CONFIG_BACK_TRACE_DEPTH_LIMIT 8
#define CONFIG_WHC_INTF_IPC_MENU 1
#define CONFIG_CORE_AS_AP 1
#define CONFIG_WLAN_MENU 1
#define CONFIG_NORMAL_SDK 1
#define CONFIG_WLAN 1
#define CONFIG_WHC_INTF_IPC 1
#define CONFIG_WHC_HOST 1
//#define CONFIG_LWIP_LAYER 1  // not set in zephyr
#define CONFIG_LWIP_NETCONN_SEM_PER_THREAD_MENU 1
#define CONFIG_LWIP_NETCONN_SEM_PER_THREAD 1
#define CONFIG_LINK_ROM_SYMB 1
#define CONFIG_CPU_HAS_FPU 1
#define CONFIG_ARM_CORE_CM4 1
#define CONFIG_AMEBADPLUS_B_CUT 1
#include <zephyr/autoconf.h>
