/*
 * Copyright (c) 2026 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Minimal platform configuration for amebasmart Zephyr build.
 */

#define CONFIG_AMEBASMART 1
#define CONFIG_SUPPORT_NAND_FLASH 1
#define CONFIG_SUPPORT_FATFS_USB 1
#define CONFIG_SUPPORT_SD_CARD 1
#define CONFIG_SUPPORT_USB 1
#define CONFIG_SUPPORT_USB_SHARED_DFIFO 1
#define CONFIG_SUPPORT_USBD_UAC 1
#define CONFIG_SUPPORT_AUDIO_FOR_USB 1
#define CONFIG_SUPPORT_USBD_MSC_SECOND_FLASH 1
#define CONFIG_SUPPORT_USBH_UAC 1
#define CONFIG_SUPPORT_USBH_ECM 1
#define CONFIG_SUPPORT_USBH_ECM_BRIDGE 1
#define CONFIG_SUPPORT_SDIOH 1
#define CONFIG_SUPPORT_SMP 1
#define CONFIG_SUPPORT_AUDIO_DEVICE 1
#define CONFIG_SUPPORT_AUDIO_CMD_ARECORD 1
#define CONFIG_SUPPORT_AUDIO_CMD_APLAY 1
#define CONFIG_SUPPORT_AUDIO_CMD_EQUALIZER 1
#define CONFIG_SUPPORT_AUDIO_CMD_PLAYER 1
#define CONFIG_SUPPORT_AUDIO_CMD_PCRECORD 1
#define CONFIG_IMG1_SRAM 1
#define CONFIG_IMG2_PSRAM 1
#define CONFIG_SUPPORT_ATCMD 1
#define CONFIG_ATCMD_MANUAL_TEST 1
#define CONFIG_ATCMD_NETWORK 1
#define CONFIG_ASSERTION_ENABLE 1
#define CONFIG_BACK_TRACE_DEPTH_LIMIT 8
#define CONFIG_DEFAULT_HEAP5 1
#define CONFIG_OTA_SWITCH_STRATEGY 1
#define CONFIG_OTA_SWITCH_BY_VERSION 1
#define CONFIG_FLASH_BOOT_OFFSET 0x8000000
#define CONFIG_FLASH_BOOT_SIZE 0x40000
#define CONFIG_FLASH_OTA1_OFFSET 0x8040000
#define CONFIG_FLASH_OTA1_SIZE 0x2C0000
#define CONFIG_FLASH_BOOT_OTA2_OFFSET 0x8300000
#define CONFIG_FLASH_BOOT_OTA2_SIZE 0x40000
#define CONFIG_FLASH_OTA2_OFFSET 0x8340000
#define CONFIG_FLASH_OTA2_SIZE 0x2C0000
#define CONFIG_FLASH_USER_OFFSET 0x0
#define CONFIG_FLASH_USER_SIZE 0x0
/* WHC role: the CA32 runs the host side; the KM4 NP build (CONFIG_AS_INIC_NP,
 * from Kconfig autoconf) runs the device side and has no TCP/IP stack.
 */
#ifdef CONFIG_AS_INIC_NP
#define CONFIG_WHC_DEV 1
#define CONFIG_WIFI_AP_STA_NUM 12
#else
#define CONFIG_WHC_HOST 1
#define CONFIG_WHC_WIFI_API_PATH 1
#define CONFIG_LWIP_LAYER 1
#endif
#define CONFIG_WLAN_CRITICAL_CODE_IN_RAM 1
#define CONFIG_WLAN 1
#define CONFIG_WHC_INTF_IPC 1
#define CONFIG_SHELL_TASK_STACK_BASIC_SIZE 1376
#define CONFIG_PBUF_POOL_BUFSIZE 508
//#define CONFIG_BT_COEXIST 1
//#define CONFIG_COEXIST_HOST 1
#define CONFIG_RSIP_SINGLE_KEY 1
#define CONFIG_FPGA 1
#define CONFIG_LINK_ROM_SYMB 1
#define CONFIG_NEON 1
#define CONFIG_SMP_DUAL_CORE 1
#define CONFIG_CORE_NUM 2
